"""
Visual Diversity Engine v2: PHOTOREALISTIC + HUMAN-FIRST visuals.

The old system was producing the same "glowing blue neural network / electrical wires"
on every post. This rewrite focuses on:
  1. Real-world photography — NOT 3D renders or sci-fi
  2. Human presence — people, offices, cities, real environments
  3. Extreme variety — 12+ distinct visual "worlds" that rotate
  4. Explicit blacklist — bans the overused motifs
  5. Topic-aware scene selection — each topic gets a unique visual metaphor
"""

from __future__ import annotations

import json
import hashlib
import random
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# ── BLACKLIST: motifs that make every post look the same ─────────────────

_BANNED_MOTIFS = (
    "ABSOLUTE VISUAL BANS (these have been overused and make the grid look robotic):\n"
    "- NO glowing neural networks or brain visualizations\n"
    "- NO electrical wires, fiber optic cables, or glowing circuit boards\n"
    "- NO blue/cyan glowing orbs or spheres\n"
    "- NO generic 3D renders of abstract tech shapes\n"
    "- NO matrix-style falling data or code rain\n"
    "- NO holographic floating UI panels\n"
    "- NO cyberpunk neon cityscapes\n"
    "- NO identical dark backgrounds with single glowing object\n"
    "- NO stock-photo-style 'hand touching screen' or 'person staring at hologram'\n"
    "The image must look like it was shot by a professional photographer, NOT generated by AI.\n"
)

# ── 12 distinct visual "worlds" ──────────────────────────────────────────
# Each world is a complete photographic direction that feels totally different.
# The system picks one per POST (not per slide) to ensure carousel coherence,
# then varies camera/lighting within the world for per-slide diversity.

VISUAL_WORLDS: List[Dict[str, Any]] = [
    {
        "id": "editorial_office",
        "name": "Modern Office Editorial",
        "prompt": (
            "Professional editorial photograph inside a modern tech company office. "
            "Clean open-plan workspace with natural daylight from floor-to-ceiling windows, "
            "warm wood and concrete materials, potted plants, whiteboards with notes. "
            "Shot on Canon EOS R5, 35mm lens, f/2.8, natural color grading. "
            "Feels like a Bloomberg or Wired magazine feature photo."
        ),
        "mood": "professional, warm, authentic",
    },
    {
        "id": "city_golden_hour",
        "name": "City Skyline at Golden Hour",
        "prompt": (
            "Stunning panoramic cityscape at golden hour. Modern skyscrapers reflecting "
            "warm sunset light, deep orange and purple sky, aerial or rooftop perspective. "
            "Real-world urban environment like San Francisco, London, or Singapore. "
            "Professional landscape/architectural photography, Sony A7R IV, 24-70mm lens. "
            "Cinematic color grade, no artificial effects."
        ),
        "mood": "ambitious, expansive, golden warmth",
    },
    {
        "id": "minimal_workspace",
        "name": "Clean Minimal Workspace",
        "prompt": (
            "Ultra-clean minimalist workspace photograph. Single MacBook or laptop on a "
            "wooden desk, coffee cup, small plant, soft diffused window light. "
            "Scandinavian design aesthetic, muted neutral tones (white, beige, light grey). "
            "Shot like a lifestyle brand campaign. 50mm lens, shallow depth of field. "
            "Calm, focused, premium."
        ),
        "mood": "calm, focused, premium lifestyle",
    },
    {
        "id": "conference_stage",
        "name": "Tech Conference Stage",
        "prompt": (
            "Professional event photography at a major tech conference or keynote. "
            "Large modern stage with dramatic spotlighting, audience silhouettes in foreground, "
            "large LED screen in background. Shot like Apple WWDC or Google I/O press photo. "
            "Canon 70-200mm f/2.8, shallow DoF, editorial event coverage quality."
        ),
        "mood": "exciting, industry-scale, newsworthy",
    },
    {
        "id": "street_documentary",
        "name": "Urban Street Documentary",
        "prompt": (
            "Documentary-style street photograph in a modern tech hub district. "
            "Pedestrians walking past modern glass buildings, genuine urban atmosphere, "
            "natural cloudy-day lighting, reflections in puddles or windows. "
            "Feels like a Reuters or AP wire photo. Leica Q2, 28mm, reportage style. "
            "Real people (shown from behind or as silhouettes), authentic street life."
        ),
        "mood": "authentic, human, journalistic",
    },
    {
        "id": "abstract_material",
        "name": "Abstract Material Close-up",
        "prompt": (
            "Extreme close-up macro photograph of an interesting material or texture. "
            "Could be: brushed aluminum surface, liquid mercury ripples, cracked glass, "
            "water droplets on a dark surface, silk fabric folds, concrete with gold leaf. "
            "Studio lighting, 100mm macro lens, razor-sharp focus, abstract composition. "
            "Premium product photography aesthetic. Minimal, textural, tactile."
        ),
        "mood": "premium, tactile, abstract",
    },
    {
        "id": "aerial_landscape",
        "name": "Aerial Landscape",
        "prompt": (
            "Breathtaking aerial photograph of a landscape from drone perspective. "
            "Could be: vast desert with geometric solar farm, sprawling green farmland "
            "with roads cutting through, coastal city from above, mountain valley at sunrise. "
            "DJI Mavic 3, natural daylight, rich saturated colors. "
            "National Geographic quality, sense of scale and wonder."
        ),
        "mood": "vast, awe-inspiring, natural beauty",
    },
    {
        "id": "lab_research",
        "name": "Research Laboratory",
        "prompt": (
            "Realistic photograph inside a modern research laboratory or clean room. "
            "Scientist or engineer (shown from behind / partial view) examining equipment. "
            "Clean white environment, safety glasses and lab coat, precision instruments. "
            "Feels like a Nature or Science Magazine feature. "
            "Nikon D850, 85mm, environmental portrait style, clinical but human."
        ),
        "mood": "scientific, precise, human element",
    },
    {
        "id": "dark_moody_still",
        "name": "Dark Moody Still Life",
        "prompt": (
            "Dramatic dark still-life photograph with a single focal object. "
            "Could be: a vintage typewriter, a chess piece, a glass sphere, a compass, "
            "a pocket watch, a single book. Dark background, single directional light source, "
            "deep shadows, chiaroscuro lighting. Shot like a Vanity Fair editorial. "
            "Phase One IQ4, 80mm, f/4. Moody, contemplative, high-art quality."
        ),
        "mood": "dramatic, contemplative, editorial",
    },
    {
        "id": "nature_tech",
        "name": "Nature Meets Technology",
        "prompt": (
            "Beautiful photograph blending natural environment with subtle technology. "
            "Could be: a solar panel field at sunrise, wind turbines against dramatic sky, "
            "a modern glass building surrounded by forest, a satellite dish in a remote valley. "
            "Real location photography, golden or blue-hour light, epic composition. "
            "Sony 24-70mm GM, landscape orientation adapted to portrait crop. Inspiring."
        ),
        "mood": "harmonious, sustainable, inspiring",
    },
    {
        "id": "architecture_interior",
        "name": "Modern Architecture Interior",
        "prompt": (
            "Stunning interior architectural photograph. Could be: a modern museum atrium, "
            "a tech company headquarters lobby, a contemporary library, a co-working space. "
            "Dramatic geometry, natural light streaming through skylights, human scale shown "
            "by small figures. Architectural Digest quality. "
            "Tilt-shift lens, 17mm, perfect verticals, wide dynamic range."
        ),
        "mood": "grand, precise, architectural beauty",
    },
    {
        "id": "human_silhouette",
        "name": "Human Silhouette Moment",
        "prompt": (
            "Powerful silhouette photograph of a person in a meaningful moment. "
            "Person standing at a large window looking out at a city or landscape, "
            "or walking through a modern corridor with dramatic backlighting. "
            "Strong compositional lines, warm rim lighting, contemplative mood. "
            "35mm film grain aesthetic, Fujifilm X-T5. Feels cinematic and human."
        ),
        "mood": "human, cinematic, contemplative",
    },
]

# ── Per-slide variation within a world ───────────────────────────────────

_SLIDE_VARIATIONS = {
    1: {  # HOOK — most dramatic
        "instruction": (
            "HOOK SLIDE: Make this the most visually striking image. "
            "Use bold contrast, dramatic lighting, strong focal point. "
            "The viewer must stop scrolling instantly."
        ),
        "framing": ["wide cinematic", "low angle looking up", "centered symmetrical"],
    },
    2: {  # CONTEXT — different angle
        "instruction": (
            "CONTEXT SLIDE: Shift perspective from the hook. Use a different angle, "
            "perhaps closer or from a unique viewpoint. Slightly simpler composition."
        ),
        "framing": ["medium close-up", "over-the-shoulder", "top-down detail"],
    },
    3: {  # INSIGHT — calmer
        "instruction": (
            "INSIGHT SLIDE: Create a calm, contemplative visual. Softer lighting, "
            "more breathing room, gentler tones. The background should aid readability."
        ),
        "framing": ["eye-level intimate", "macro texture detail", "wide with negative space"],
    },
    4: {  # CTA — clean
        "instruction": (
            "CTA SLIDE: Clean, minimal background. Lots of empty space for text. "
            "Subtle, elegant visual element — not competing with the call to action."
        ),
        "framing": ["minimal centered", "soft bokeh background", "gentle gradient atmosphere"],
    },
}


def _get_slide_variation(slide_index: int, total_slides: int, rng: random.Random) -> Dict:
    """Get slide-specific variation rules."""
    if slide_index == 1:
        return _SLIDE_VARIATIONS[1]
    elif slide_index == total_slides:
        return _SLIDE_VARIATIONS[4]
    elif slide_index == 2:
        return _SLIDE_VARIATIONS[2]
    else:
        return _SLIDE_VARIATIONS[3]


def _pick_world(topic: str, rng: random.Random) -> Dict[str, Any]:
    """Pick a visual world based on topic hash for consistency within a post,
    but different across posts."""
    # Use topic hash to get consistent world for all slides of same post
    topic_hash = int(hashlib.md5(topic.encode()).hexdigest(), 16)
    # Add time-based salt so same topic on different days gets different world
    day_salt = int(time.time()) // 86400
    idx = (topic_hash + day_salt) % len(VISUAL_WORLDS)
    return VISUAL_WORLDS[idx]


def build_diverse_prompt(
    content_type: str,
    topic: str,
    slide_index: int,
    total_slides: int,
    visual_hint: str = "",
    rng: Optional[random.Random] = None,
) -> str:
    """Build a photorealistic, human-first image prompt with extreme variety."""
    if rng is None:
        rng = random.Random(int(time.time() * 1000) + slide_index)

    # Pick a visual world (consistent per-post, varies across posts)
    world = _pick_world(topic, rng)

    # Get slide-specific variation
    slide_var = _get_slide_variation(slide_index, total_slides, rng)
    framing = rng.choice(slide_var["framing"])

    # Build the prompt — IGNORE the visual_hint from story brief if it contains
    # banned motifs (which it almost always does since it was trained on the old style)
    hint_block = ""
    if visual_hint:
        # Only use the hint if it doesn't contain banned motifs
        banned_words = {"glowing", "neural", "circuit", "holographic", "neon", "cyber",
                        "matrix", "wireframe", "fiber optic", "electrical", "3d render"}
        hint_lower = visual_hint.lower()
        if not any(bw in hint_lower for bw in banned_words):
            hint_block = f"Editorial context: {visual_hint}\n\n"

    prompt = f"""{hint_block}Topic context: {topic}

PHOTOGRAPHIC DIRECTION:
{world['prompt']}

Framing for this slide: {framing}
{slide_var['instruction']}
Mood: {world['mood']}

{_BANNED_MOTIFS}
COMPOSITION RULE: Keep the main subject/action in the upper 60-65% of the frame.
The bottom 30% must be relatively dark, clean, or uncluttered for text overlay.

OUTPUT: A single photorealistic image that looks like it was taken by a professional
photographer for a premium editorial publication. NOT a 3D render. NOT AI-generated looking.
""".strip()

    return prompt


# ── Prompt history deduplication ─────────────────────────────────────────

def deduplicate_against_history(
    prompt: str,
    history_path: Path,
    max_history: int = 8,
    rng: Optional[random.Random] = None,
) -> str:
    """
    Check if the same visual world was used recently. If so, pick a different one.
    Saves prompt to history for future dedup.
    """
    if rng is None:
        rng = random.Random()

    history: List[str] = []
    if history_path.exists():
        try:
            data = json.loads(history_path.read_text(encoding="utf-8"))
            if isinstance(data, list):
                history = [str(h) for h in data[-max_history:]]
        except (json.JSONDecodeError, OSError):
            history = []

    # Check if same world ID was used recently
    current_world_ids = [w["id"] for w in VISUAL_WORLDS if w["prompt"][:60] in prompt]
    if current_world_ids:
        current_id = current_world_ids[0]
        recent_ids = []
        for h in history[-3:]:  # Check last 3 posts
            for w in VISUAL_WORLDS:
                if w["prompt"][:60] in h:
                    recent_ids.append(w["id"])
                    break
        if current_id in recent_ids:
            # Same world used recently — pick a different one
            available = [w for w in VISUAL_WORLDS if w["id"] not in recent_ids]
            if available:
                new_world = rng.choice(available)
                prompt = prompt.replace(
                    next(w["prompt"] for w in VISUAL_WORLDS if w["id"] == current_id),
                    new_world["prompt"],
                )

    # Save to history
    history.append(prompt)
    history = history[-max_history:]
    history_path.parent.mkdir(parents=True, exist_ok=True)
    history_path.write_text(json.dumps(history, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    return prompt


# ── Content type heuristic fallback ──────────────────────────────────────

_FOUNDER_KEYWORDS = {"ceo", "founder", "cto", "leadership", "sam altman", "elon musk",
                     "sundar pichai", "satya nadella", "jensen huang", "mark zuckerberg",
                     "tim cook", "visionary", "co-founder", "chairman"}
_PRODUCT_KEYWORDS = {"launch", "launches", "product", "release", "update", "feature",
                     "app", "device", "chip", "model", "version", "tool", "platform",
                     "sdk", "api", "plugin", "integration"}
_INFRA_KEYWORDS = {"data center", "datacenter", "server", "cloud", "infrastructure",
                   "semiconductor", "fab", "network", "compute", "gpu cluster",
                   "hyperscaler", "bandwidth", "capacity"}
_INSIGHT_KEYWORDS = {"study", "research", "survey", "report", "analysis", "paper",
                     "benchmark", "comparison", "trend", "forecast", "statistic"}


def classify_content_type(topic: str, body: str = "") -> str:
    """Keyword-based fallback when the strategist doesn't provide content_visual_type."""
    combined = (topic + " " + body).lower()

    if any(kw in combined for kw in _FOUNDER_KEYWORDS):
        return "founder"
    if any(kw in combined for kw in _INFRA_KEYWORDS):
        return "infrastructure"
    if any(kw in combined for kw in _PRODUCT_KEYWORDS):
        return "product"
    if any(kw in combined for kw in _INSIGHT_KEYWORDS):
        return "insight"
    return "news"
